# Generated by Django 2.1.7 on 2019-03-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwiches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Donuts',
        ),
    ]
