# Generated by Django 2.1.7 on 2019-03-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0002_auto_20190324_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='donuts',
            name='price',
            field=models.FloatField(default=1.49),
        ),
    ]
