# Generated by Django 2.1.7 on 2019-03-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0003_auto_20190327_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sandwiches',
            new_name='Savories',
        ),
        migrations.RenameModel(
            old_name='Donuts',
            new_name='Sweets',
        ),
    ]
