# Generated by Django 2.1.7 on 2019-03-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0004_auto_20190327_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='Savories',
            new_name='Savory',
        ),
        migrations.RenameModel(
            old_name='Sweets',
            new_name='Sweet',
        ),
    ]
