# Generated by Django 2.1.7 on 2019-03-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0005_auto_20190327_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savory',
            options={'verbose_name_plural': 'savories'},
        ),
    ]
