# Generated by Django 2.2.1 on 2019-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0006_auto_20190327_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savory',
            name='offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='offered',
            field=models.BooleanField(default=True),
        ),
    ]
