# Generated by Django 2.2.1 on 2019-05-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0008_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home Page Text', 'verbose_name_plural': 'Home Page Text'},
        ),
    ]
